In [1]:
print("Bienvenidos al Cebollitas F.C")

Bienvenidos al Cebollitas F.C

In [2]:
import pandas as pd
import os

In [3]:
# Definimos la ruta relativa
# .. (sale de notebooks) / data / raw / archivo.csv
ruta_datos = "../data/raw/partidos_cebollitas.csv"

# Verificamos si el archivo existe antes de cargarlo
if os.path.exists(ruta_datos):
    df = pd.read_csv(ruta_datos)
    print("✅ ¡Dataset cargado con éxito!")
    # Mostramos las primeras 5 filas
    display(df.head())
else:
    print(f"❌ No encontré el archivo en: {os.path.abspath(ruta_datos)}")

✅ ¡Dataset cargado con éxito!

,fecha_partido,equipo_local,equipo_visitante,goles_local,goles_visitante,posesion_local (%),posesion_visitante (%),tiros_arco_local,tiros_arco_visitante,estadio
0,2023-01-01,Atlético Python,Cebollitas FC,2,0,54,46,12,6,Python Arena
1,2023-01-08,NumPy City,Atlético Python,1,5,60,40,12,3,Estadio ML
2,2023-01-15,Cebollitas FC,Data United,1,0,55,45,10,7,Python Arena
3,2023-01-22,Atlético Python,Data United,2,3,57,43,3,3,Campo Pandas
4,2023-01-29,Data United,Cebollitas FC,5,3,52,48,7,12,Estadio ML

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   fecha_partido           100 non-null    object
 1   equipo_local            100 non-null    object
 2   equipo_visitante        100 non-null    object
 3   goles_local             100 non-null    int64
 4   goles_visitante         100 non-null    int64
 5   posesion_local (%)      100 non-null    int64
 6   posesion_visitante (%)  100 non-null    int64
 7   tiros_arco_local        100 non-null    int64
 8   tiros_arco_visitante    100 non-null    int64
 9   estadio                 100 non-null    object
dtypes: int64(6), object(4)
memory usage: 7.9+ KB

In [5]:
df.isnull().sum()

fecha_partido             0
equipo_local              0
equipo_visitante          0
goles_local               0
goles_visitante           0
posesion_local (%)        0
posesion_visitante (%)    0
tiros_arco_local          0
tiros_arco_visitante      0
estadio                   0
dtype: int64

In [6]:
pd.unique(df['equipo_local'])

array(['Atlético Python', 'NumPy City', 'Cebollitas FC', 'Data United',
       'Real Pandas'], dtype=object)

In [7]:
pd.unique(df['equipo_visitante'])

array(['Cebollitas FC', 'Atlético Python', 'Data United', 'Real Pandas',
       'NumPy City'], dtype=object)

In [8]:
df = pd.get_dummies(df,columns=['equipo_local','equipo_visitante'])

In [9]:
df.head()

,fecha_partido,goles_local,goles_visitante,posesion_local (%),posesion_visitante (%),tiros_arco_local,tiros_arco_visitante,estadio,equipo_local_Atlético Python,equipo_local_Cebollitas FC,equipo_local_Data United,equipo_local_NumPy City,equipo_local_Real Pandas,equipo_visitante_Atlético Python,equipo_visitante_Cebollitas FC,equipo_visitante_Data United,equipo_visitante_NumPy City,equipo_visitante_Real Pandas
0,2023-01-01,2,0,54,46,12,6,Python Arena,True,False,False,False,False,False,True,False,False,False
1,2023-01-08,1,5,60,40,12,3,Estadio ML,False,False,False,True,False,True,False,False,False,False
2,2023-01-15,1,0,55,45,10,7,Python Arena,False,True,False,False,False,False,False,True,False,False
3,2023-01-22,2,3,57,43,3,3,Campo Pandas,True,False,False,False,False,False,False,True,False,False
4,2023-01-29,5,3,52,48,7,12,Estadio ML,False,False,True,False,False,False,True,False,False,False

In [10]:
df[df.duplicated()]

Empty DataFrame
Columns: [fecha_partido, goles_local, goles_visitante, posesion_local (%), posesion_visitante (%), tiros_arco_local, tiros_arco_visitante, estadio, equipo_local_Atlético Python, equipo_local_Cebollitas FC, equipo_local_Data United, equipo_local_NumPy City, equipo_local_Real Pandas, equipo_visitante_Atlético Python, equipo_visitante_Cebollitas FC, equipo_visitante_Data United, equipo_visitante_NumPy City, equipo_visitante_Real Pandas]
Index: []

In [11]:
df['fecha_partido'] = pd.to_datetime(df['fecha_partido'],errors='coerce')

In [13]:
df.head()

,fecha_partido,goles_local,goles_visitante,posesion_local (%),posesion_visitante (%),tiros_arco_local,tiros_arco_visitante,estadio,equipo_local_Atlético Python,equipo_local_Cebollitas FC,equipo_local_Data United,equipo_local_NumPy City,equipo_local_Real Pandas,equipo_visitante_Atlético Python,equipo_visitante_Cebollitas FC,equipo_visitante_Data United,equipo_visitante_NumPy City,equipo_visitante_Real Pandas
0,2023-01-01,2,0,54,46,12,6,Python Arena,True,False,False,False,False,False,True,False,False,False
1,2023-01-08,1,5,60,40,12,3,Estadio ML,False,False,False,True,False,True,False,False,False,False
2,2023-01-15,1,0,55,45,10,7,Python Arena,False,True,False,False,False,False,False,True,False,False
3,2023-01-22,2,3,57,43,3,3,Campo Pandas,True,False,False,False,False,False,False,True,False,False
4,2023-01-29,5,3,52,48,7,12,Estadio ML,False,False,True,False,False,False,True,False,False,False

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 18 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   fecha_partido                     100 non-null    datetime64[ns]
 1   goles_local                       100 non-null    int64
 2   goles_visitante                   100 non-null    int64
 3   posesion_local (%)                100 non-null    int64
 4   posesion_visitante (%)            100 non-null    int64
 5   tiros_arco_local                  100 non-null    int64
 6   tiros_arco_visitante              100 non-null    int64
 7   estadio                           100 non-null    object
 8   equipo_local_Atlético Python      100 non-null    bool
 9   equipo_local_Cebollitas FC        100 non-null    bool
 10  equipo_local_Data United          100 non-null    bool
 11  equipo_local_NumPy City           100 non-null    bool
 12  equipo_local_Real Pandas          100 non-null    bool
 13  equipo_visitante_Atlético Python  100 non-null    bool
 14  equipo_visitante_Cebollitas FC    100 non-null    bool
 15  equipo_visitante_Data United      100 non-null    bool
 16  equipo_visitante_NumPy City       100 non-null    bool
 17  equipo_visitante_Real Pandas      100 non-null    bool
dtypes: bool(10), datetime64[ns](1), int64(6), object(1)
memory usage: 7.4+ KB